apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/himanshunc/EKS.git
    targetRevision: main
    path: k8s/nodeapp
  destination:
    server: https://kubernetes.default.svc
    namespace: nodeapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
